name: sindoexpress
description: Sindo Express Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_money_formatter: ^0.8.2
  modal_progress_hud: ^0.1.3
  dio: ^3.0.3
  http: ^0.12.0+2
  localstorage: ^2.0.0
  shared_preferences: ^0.5.3+4
  flutter_html: ^0.11.0
  flutter_open_whatsapp: ^0.1.2
  material_design_icons_flutter: 3.2.4495
  flutter_qr_scanner: ^0.1.5
#  # intl: ^0.15.8
  video_player: ^0.10.8+1
  url_launcher: ^5.4.1
  flutter_svg: ^0.15.0
 # cupertino_icons: ^0.1.2
  flutter_youtube: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/splash_screen.png
    - assets/sindo-express-text.png
    - assets/news.png
    - assets/notification.png
    - assets/tracking.png
    - assets/schedule.png
    - assets/aboutus.png
    - assets/header.png
    - assets/background.png
    - assets/icon_container.png
    - assets/cruise.svg
    - assets/cruise-1.svg
    - assets/gallery.jpeg
    - assets/contact.png
    - assets/callcenter.png
    - assets/intro.mp4
    - assets/home.png
    # - assets/home-1.png
    - assets/message.png
    - assets/message-1.png
    - assets/profile-1.png
    - assets/profile.png
    - assets/homeicon.png
    - assets/sosmedicon.png
    - assets/accicon.png
    - assets/background01.jpg
    - assets/background02.jpg
    - assets/background03.jpg
    - assets/contactbranch.png
    - assets/compro.png
    - assets/ourclient.png
    - assets/sindocopyrightlogo.png
    - assets/contactandbranches.png
    - assets/ourclients.png
    - assets/generalcargotabicon.png
    - assets/cars.png
    - assets/motorcycle.png
    - assets/heavydutyshipmenttabicon.png
    - assets/ourfleettabicon.png
    - assets/holiday.png
    - assets/promo.png
    - assets/others.png
    - assets/fb.png
    - assets/ig.png
    - assets/web.png
    - assets/yt.png
    - assets/Qr.png
    - assets/iconusername.png
    - assets/iconpassword.png
    - assets/loginbtn.png
    - assets/csicon.png
  fonts:
    - family : Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 100
        - asset: assets/fonts/Montserrat-Black.otf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Light.otf
          weight: 400
        - asset: assets/fonts/Montserrat-LightItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.otf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Thin.otf
          weight: 200
        - asset: assets/fonts/Montserrat-ThinItalic.otf
          weight: 200
          style: italic
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
